FROM node:20-slim AS build
WORKDIR /app
COPY front/package.json front/package-lock.json ./
RUN npm ci
COPY front/ .
RUN npx expo export:web

FROM nginx:alpine
COPY nginx/prod.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/web-build /usr/share/nginx/html
EXPOSE 80
