services:

  sotc-backend:
    container_name: sotc-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    networks:
      - sotc-net

  sotc-nginx:
    container_name: sotc-nginx
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - sotc-backend
    networks:
      - sotc-net

networks:
  sotc-net:
    driver: bridge
