const cardImages = {
    ApartheidCard: require('../assets/images/cards/implemented/ApartheidCard.png'),
    BarricadeCard: require('../assets/images/cards/implemented/BarricadeCard.png'),
    BlackHoleCard: require('../assets/images/cards/implemented/BlackHoleCard.png'),
    BombardCard: require('../assets/images/cards/implemented/BombardCard.png'),
    BombingCard: require('../assets/images/cards/implemented/BombingCard.png'),
    CavalcadeCard: require('../assets/images/cards/implemented/CavalcadeCard.png'),
    ChargeCard: require('../assets/images/cards/implemented/ChargeCard.png'),
    CourtlyLoveCard: require('../assets/images/cards/implemented/CourtlyLoveCard.png'),
    CrabCard: require('../assets/images/cards/implemented/CrabCard.png'),
    HomeCard: require('../assets/images/cards/implemented/HomeCard.png'),
    KangarooCard: require('../assets/images/cards/implemented/KangarooCard.png'),
    LightweightSquadCard: require('../assets/images/cards/implemented/LightweightSquadCard.png'),
    MadHorseDiseaseCard: require('../assets/images/cards/implemented/MadHorseDiseaseCard.png'),
    MadHouseCard: require('../assets/images/cards/implemented/MadHouseCard.png'),
    MagnetismCard: require('../assets/images/cards/implemented/MagnetismCard.png'),
    ManHoleCard: require('../assets/images/cards/implemented/ManHoleCard.png'),
    MercyCard: require('../assets/images/cards/implemented/MercyCard.png'),
    NeutralityCard: require('../assets/images/cards/implemented/NeutralityCard.png'),
    NuclearBombCard: require('../assets/images/cards/implemented/NuclearBombCard.png'),
    PegasusCard: require('../assets/images/cards/implemented/PegasusCard.png'),
    QuadrilleCard: require('../assets/images/cards/implemented/QuadrilleCard.png'),
    ReflectedBishopCard: require('../assets/images/cards/implemented/ReflectedBishopCard.png'),
    SelfDefenseCard: require('../assets/images/cards/implemented/SelfDefenseCard.png'),
    StableCard: require('../assets/images/cards/implemented/StableCard.png'),
    VampirismCard: require('../assets/images/cards/implemented/VampirismCard.png'),
};

export default cardImages;
